### ISSUE TITLE
1.16.1 Base64 Textures Broken.

### ISSUE THREAD

**Issue by prosavage** [Deanveloper/SkullCreator#5]
Heyo --

The skull's from base64 in 1.16.1 do not work at all.
They just come up as empty player heads.

I looked into it, and it seems the code for getting most significant bits is wrong, I compared it to head database website's 1.16 nbt data.

An Example: 
https://minecraft-heads.com/custom-heads/alphabet/8782-black-forward

This is what SkullCreator Generates:
```json
{SkullOwner:{Id:[I;1787609467,0,1787609467,0],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDllY2NjNWMxYzc5YWE3ODI2YTE1YTdmNWYxMmZiNDAzMjgxNTdjNTI0MjE2NGJhMmFlZjQ3ZTVkZTlhNWNmYyJ9fX0="}]}}}
```

This is valid data:
```json
SkullOwner:{Id:[I;-886489585,-502644074,-1943245271,-436273173],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDllY2NjNWMxYzc5YWE3ODI2YTE1YTdmNWYxMmZiNDAzMjgxNTdjNTI0MjE2NGJhMmFlZjQ3ZTVkZTlhNWNmYyJ9fX0="}]}}
```

You can see the different at the Id phase.

**Comment by deanveloper** [comment]
Thank you for the information, someone made a PR for 1.16 support, and said that it was tested and works, so I had accepted it without testing for myself... Once I’m at my I’ll make a fix for this myself and test it. Sorry for the inconvenience

**Comment by prosavage** [comment]
I had an issue myself on 1.16.1 Paper actually.
I have change the code since to something else: 
```java
UUID hashAsId = new UUID(base64.hashCode(), base64.hashCode());
		if (Bukkit.getVersion().contains("1.16")) {
			int first = (int) (hashAsId.getMostSignificantBits() >>> 32);
			int second = (int) (hashAsId.getMostSignificantBits() & 0xffffffff);
			int third = (int) (hashAsId.getLeastSignificantBits() >>> 32);
			int fourth = (int) (hashAsId.getLeastSignificantBits() & 0xffffffff);

			return Bukkit.getUnsafe().modifyItemStack(item,
					"{SkullOwner:{Id:[I;" + first + "," + second + "," + third + "," + fourth + "],Properties:{textures:[{Value:\"" + base64 + "\"}]}}}"
			);
		} else {
			return Bukkit.getUnsafe().modifyItemStack(item,
					"{SkullOwner:{Id:\"" + hashAsId + "\",Properties:{textures:[{Value:\"" + base64 + "\"}]}}}"
			);
		}
```

**Comment by prosavage** [comment]
I looked into it, and the Id doesnt matter, but we want something generated to prevent collisions.

**Comment by deanveloper** [comment]
Ah right, I remember now. Yeah the `Id` field doesn't really do much besides prevent collisions with other minecraft heads. Honestly, the `Value` field should really be able to that job IMO, since two heads with the same `Value` should be able to stack with the same head. But Mojang is weird I guess and has the `Id` field as well.

Anyway, here is my progress so far.
Plugin is using legacy bukkit API on a 1.16 server: 
![image](https://user-images.githubusercontent.com/3196327/86417452-a9e7a880-bc92-11ea-99e4-d775053c68f7.png)

The skull is being set to `minecraft:skeleton_skull` when it should be `minecraft:player_skull`. Ugh.

**Comment by deanveloper** [comment]
Seems that this issue primarily occurs when using the legacy API on newer bukkit versions. When using the plugin with `plugin-api: "1.13"`, the issue doesn't seem to occur.
I might have to maintain two separate versions.

**Comment by deanveloper** [comment]
I've made a decision that the `master` branch will contain the 1.13+ version of the plugin, and will be given version number 3.0.

The legacy for 1.12-, it will have version 2.1 after I am done working through this.

Having two versions may be easier since I don't have to do so many dynamic version checks. Still one for the 1.16 check, but that's not a big check so I am not worried.

**Comment by deanveloper** [comment]
Actually, I may have found a way to do this without anything too messy. Trying out some reflection stuff.

**Comment by prosavage** [comment]
That's great to hear.

**Comment by deanveloper** [comment]
I'm happy to announce that I think I have something working! Unfortunately using legacy API (1.12 and older) on newer versions (1.13 and newer) will not work, however. I have tried this time and time again and there doesn't seem to be a way to get it to work. However, as long as one uses the legacy API on 1.12 and the 1.13 API on 1.13+, it should work fine.

Tested on versions 1.12.2 and 1.16.1, however none of the versions in between. But it _should_ work fine on the versions in between, AND we now have the benefit of it working across worlds instead of only in the main world since it no longer uses commands to edit skulls.

**Comment by deanveloper** [comment]
Publishing now!

**Comment by prosavage** [comment]
So for building a project with cross version support I would need to use both of your legacy and the new API.

I was having issues getting the dependencies on bintray, not sure if that is fixed now.
But is it okay if I compile these from source and host them on my nexus?

**Comment by deanveloper** [comment]
That's 100% alright with me

**Comment by deanveloper** [comment]
I'm _guessing_ it might be Mojang's authlib. Might need to do some reflection stuff to remove the dependency since I want to make sure that the maven dependency works smoothly. 3.0.1 is likely incoming soon.
